DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS section;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS userpermission;
DROP TABLE IF EXISTS useraccount;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS career;